# Generated by Django 5.1.7 on 2025-12-15 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cusine_name', models.CharField(max_length=255)),
                ('cusine_description', models.TextField()),
                ('type', models.CharField(choices=[('VEG', 'VEG'), ('NON VEG', 'NON VEG')], max_length=20)),
                ('region', models.CharField(choices=[('NORTH INDIAN', 'NORTH INDIAN'), ('SOUTH INDIAN', 'SOUTH INDIAN'), ('PUNJABI FOOD', 'PUNJABI FOOD'), ('FAST FOOD', 'FAST FOOD'), ('DESSERT', 'DESSERT'), ('SNACK', 'SNACK'), ('REGIONAL SPECIAL', 'REGIONAL SPECIAL')], max_length=20)),
                ('price', models.IntegerField()),
                ('time', models.IntegerField()),
                ('cusine_image', models.ImageField(upload_to='images/cusine_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_email', models.CharField(blank=True, max_length=64, null=True)),
                ('username', models.CharField(blank=True, max_length=16, null=True)),
                ('role', models.CharField(blank=True, default='driver', max_length=16, null=True)),
                ('driver_name', models.CharField(max_length=255)),
                ('mobile_number', models.IntegerField()),
                ('driver_image', models.ImageField(upload_to='images/driver_images/')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=7)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCreated',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('delivery_address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('is_received', models.BooleanField(default=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_started', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('is_cooking_completed', models.BooleanField(default=False)),
                ('cooking_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_out_for_delivery', models.BooleanField(default=False)),
                ('out_for_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('otp_confirmed', models.BooleanField(default=False)),
                ('delivery_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='adminapp.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver_Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='adminapp.driver')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='adminapp.ordercreated')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.cuisine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.ordercreated')),
            ],
        ),
        migrations.AddField(
            model_name='ordercreated',
            name='items',
            field=models.ManyToManyField(related_name='ordered_in', through='adminapp.OrderItem', to='adminapp.cuisine'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_number', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
